language: node_js
dist: trusty

node_js:
  - 'stable'
  - '0.12'

# Support for Google Chrome.
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install
  - npm install codeclimate-test-reporter
script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_success:
  - codeclimate-test-reporter < reports/coverage/report-lcov/lcov.info
